# Generated by Django 3.1 on 2023-03-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_completo', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenDeProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_OPR', models.CharField(max_length=200)),
                ('fecha_caducidad', models.DateField()),
                ('fecha_inicio_produccion', models.DateField(null=True)),
                ('fecha_finalizado', models.DateField(null=True)),
                ('numero_articulo_a_producir', models.IntegerField(null=True)),
                ('cantidad_articulo', models.IntegerField()),
                ('maquina_asignada', models.IntegerField()),
                ('orden_cola_produccion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'OPR',
                'verbose_name_plural': "OPR's",
            },
        ),
        migrations.CreateModel(
            name='Scatola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nro_scatola', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad', models.IntegerField()),
                ('operario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisor.operario')),
                ('opr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisor.ordendeproduccion')),
            ],
            options={
                'verbose_name': 'Scatola',
                'verbose_name_plural': 'Scatolas',
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=100)),
                ('nombre_maquina', models.CharField(max_length=250)),
                ('activo_desde', models.IntegerField()),
                ('tiempo_actual_con_articulo', models.IntegerField()),
                ('cantidad_producidos', models.IntegerField()),
                ('maquina_automatica', models.BooleanField(default=False)),
                ('operario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisor.operario')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('materia_prima_nombre', models.CharField(max_length=150)),
                ('cantidad_area', models.IntegerField()),
                ('cantidad_deposito', models.IntegerField()),
                ('tiempo_estimado_produccion', models.IntegerField(null=True)),
                ('tiempo_estimado_attressaggio', models.IntegerField(null=True)),
                ('tiempo_real_produccion', models.IntegerField(null=True)),
                ('diseño', models.FileField(upload_to='pdfs_disenios')),
                ('operario_mas_rapido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supervisor.operario')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
    ]
