# Generated by Django 3.1 on 2023-03-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeproduccion',
            name='numero_art',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
