# Generated by Django 3.2.8 on 2023-02-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='tiempo_real_attressaggio',
        ),
        migrations.AddField(
            model_name='maquina',
            name='maquina_automatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maquina',
            name='nombre_maquina',
            field=models.CharField(default='nombre_ejemplo', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordendeproduccion',
            name='nombre_OPR',
            field=models.CharField(default='nombre_ejemplo', max_length=200),
            preserve_default=False,
        ),
    ]
