# Generated by Django 3.2.8 on 2023-02-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_auto_20230222_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='ordendeproduccion',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='scatola',
            name='uuid',
        ),
    ]
