# Generated by Django 3.1 on 2023-03-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_ordendeproduccion_numero_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendeproduccion',
            name='numero_art',
        ),
        migrations.AlterField(
            model_name='ordendeproduccion',
            name='numero_articulo_a_producir',
            field=models.BigIntegerField(null=True),
        ),
    ]
