# Generated by Django 3.1 on 2023-03-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_auto_20230304_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='materia_prima_nombre',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='numero',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tiempo_estimado_attressaggio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tiempo_estimado_produccion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tiempo_real_produccion',
            field=models.IntegerField(default=0),
        ),
    ]
