# Generated by Django 3.2.8 on 2023-02-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_auto_20230222_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tiempo_estimado_attressaggio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tiempo_estimado_produccion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tiempo_real_produccion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='activo_desde',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tiempo_actual_con_articulo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordendeproduccion',
            name='fecha_finalizado',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ordendeproduccion',
            name='fecha_inicio_produccion',
            field=models.DateField(null=True),
        ),
    ]
