# Generated by Django 3.1 on 2023-03-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0004_auto_20230305_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendeproduccion',
            name='fecha_caducidad',
            field=models.DateField(null=True),
        ),
    ]
