# Generated by Django 3.1 on 2023-03-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0006_auto_20230308_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='diseño',
            new_name='disenio',
        ),
    ]
